name: Close stale issues
on:
  schedule:
    # Once per day at midnight
    - cron: "0 0 * * *"

permissions:
  issues: write

jobs:
  close-reproduction-missing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          days-before-stale: 10
          days-before-close: 0
          any-of-labels: reproduction-missing,needs-isolation
          stale-issue-message: "This issue has been automatically closed because it is currently not actionable and has become stale. If the problem persists, please create a new issue."
